# Black
[tool.black]
skip-string-normalization = true
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | migrations
)/
'''

# isort
[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = false
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88